### PR TITLE
Add modified changes by Michael Stanway

### PR DESCRIPTION
**Pull request by tatedunbar**
Redo of PR #58, which was accidentally deleted. This contains updates to Category.m, Network.m, and new tests for Category.m currently. Currently these new tests are failing, but I'm unsure why, so if someone else could look at them, that would be helpful.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@tatedunbar thanks! Have you seen the logs at https://github.com/dolphin-acoustics-vip/artwarp/actions/runs/8309001737/job/22739868982?pr=64 ? Do the errors make sense?

**Comment by tatedunbar** [comment]
@olexandr-konovalov I've looked at the errors but can't quite understand them because, as far as I can tell, I've passed the right number of arguments to add().

**Comment by olexandr-konovalov** [comment]
@tatedunbar ok, will try to look later. BTW, this is a useful post on writing commit message - the one use used in 32878db3e3bc426bdff9d1d2d183c04fc996c18a has too 1st line, and e.g. GitHub shows it in an abbreviated way...

**Comment by olexandr-konovalov** [comment]
Hm, I see... Does it work locally on your computer @tatedunbar ?
```
  ================================================================================
  Error occurred in category_test/category_test and it did not run to completion.
      ---------
      Error ID:
      ---------
      'MATLAB:TooManyInputs'
      --------------
      Error Details:
      --------------
      Error using Category/add
      Too many input arguments.
      
      Error in category_test (line 14)
      cat.add(cat, contours(2));
  ================================================================================
```

**Comment by tatedunbar** [comment]
@olexandr-konovalov no, it doesn't

**Comment by tatedunbar** [comment]
Everything seems to be working now with changes to both Category and Network.

**Comment by olexandr-konovalov** [comment]
Ok, thanks @tatedunbar. Do you plan to add more commits to this PR ?

**Comment by tatedunbar** [comment]
@olexandr-konovalov I believe that this is fully complete at this point. I've just added a couple more comments to functions.

**Pull request merged**
