### PR TITLE
Add factory methods and unit tests

### PR DESCRIPTION
**Pull request by harvard-tham**

### CODE REVIEW

**Review by olexandr-konovalov — CHANGES_REQUESTED** [review]
@harvard-tham please update PR title and edit its description to reflect the 2nd commit too

**Comment by harvard-tham** [comment]
I have updated the unit tests in `tst/`. They all pass on my machine, is there anyway to merge these unit tests too?

**Comment by harvard-tham** [comment]
> @harvard-tham unless these two commits are related or you plan to merge this into rewrite _really quickly_ avoid piling up commits in the same pull request. Imagine that the earlier commit looks good and can be merged, but the later one has some problems and needs more work. Then this would block the earlier commit appearing in `rewrite` where it may be of an interest to other collaborators. Making two separate commits in parallel or one after another from the start may be is easier.

Ok I will make separate pull requests for different features from now on

**Comment by olexandr-konovalov** [comment]
@harvard-tham we possibly don't have to call files with the `testunit_` prefix - those in `tst` will be processed automatically. I only have used that prefix to distinguish it from `test_csv` in the root directory used for the script based test.

**Review by olexandr-konovalov — CHANGES_REQUESTED** [review]
@harvard-tham Before merging, let's try to improve names of test files - see my comment above.

**Review by olexandr-konovalov — APPROVED** [review]
great - thanks @harvard-tham !

**Pull request merged**
