### PR TITLE
Add code from Wendi's version on top of Version of 2021-10-01

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
This is the 2nd version of PR #27. I have a conjecture that Wendi uses the code before GitHub was set up, so hopefully we will now clearer see the actual changes in Wendi's version, and I can then try to rebase them properly on top of the most recent changes in the code by @RohanK22 et al. 

**Update:** that's the current plan:
- [ ] Review the changes, mark those where changes have to be reverted (i.e. we need to keep the current version from GitHub, now Wendi's)
- [ ] Resolve conflicts
- [ ] Test
- [ ] Decide what to do with other files provided by Wendi.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
This makes sense, there are conflicts in 6 files which I will try to resolve, or we can try to inspect together at the next project meeting. 

Also, to remind myself, there are two more files that needs checking:

```
error: The following untracked working tree files would be overwritten by merge:
	ARTwarp.mat
	ARTwarp_Plot_Net2.m
```

**Comment by alex-konovalov** [comment]
Some files were made using an "old Mac" line endings (see https://stackoverflow.com/questions/14080306/remove-cr-line-terminators). I have detected them with
```
artwarp-alexk $ file *.m | grep 'CR line'
ARTwarp_Test_Net.m:                                            ASCII text, with CR line terminators
ARTwarp_csv.m:                                                 ASCII text, with CR line terminators
ARTwarp_txt.m:                                                 ASCII text, with CR line terminators
```
and fixed with
```
artwarp-alexk $ mac2unix ARTwarp_Test_Net.m 
mac2unix: converting file ARTwarp_Test_Net.m to Unix format...
artwarp-alexk $ mac2unix ARTwarp_csv.m 
mac2unix: converting file ARTwarp_csv.m to Unix format...
artwarp-alexk $ mac2unix ARTwarp_txt.m 
mac2unix: converting file ARTwarp_txt.m to Unix format...
```
Then I force-pushed new versions - you can see now meaningful diffs for files where before we have seen `^M` and garbled text.

Need to figure out how this happened, to avoid this in the future.

**Comment by alex-konovalov** [comment]
Below I've listed the conflicting blocks. I really hope we can then handle this at the next meeting. Some of them are easy to resolve.

- `ARTwarp_Create_Figure.m`

```
<<<<<<< HEAD
h2 = uimenu('Parent',h1, ...
    'Callback','ARTwarp_Plot_Net2', ...
    'Accelerator','p', ...
    'Label','Plot Categorisation 2', ...
    'Enable','off', ...
    'Tag','Plot2menu');
=======
%draw the contour and text in the top row of the figure
    %'Parent' is within which figure the axes belong (h0 = ARTwarp figure)
    %'Units' 'normalized' to the containing figure where 0,0 is bottom left
    %corner and 1,1 is upper right corner
    %'CameraUpVector' assigns which way is up in terms of x y z (y = 1 and
    %so is "up"
    %'CameraUpVectorMode' automatically set to 'manual' if CameraUpVector
    %is specified to override default values
    %'Position' position of axes specified by coordinates of [Left Bottom
    %Width Height] (Left = 0.01 or far left, Bottom = (rowHeight plus a
    %buffer of 0.01) * (numRows-1) or at the bottom of the top row)
    %'Tag' is the graph's name so it can be referred to by commands such as
    %'findobj'
    %'XTick' are tick mark locations on the x-axis (empty set means remove
    %tick marks)
    %'YTick' are tick mark locations on the y-axis
>>>>>>> 08305fa (Add code from Wendi's version on top of Version of 2021-10-01)
```

`ARTwarp_Load_Data.m`

```
<<<<<<< HEAD
path = [path '/*ctr'];
DATA = dir(path);
DATA = rmfield(DATA,'date');
DATA = rmfield(DATA,'datenum');
DATA = rmfield(DATA,'bytes');
DATA = rmfield(DATA,'isdir');
[numSamples x] = size(DATA);

% this line is needed to ctrick Matlab into beleiving that fcontour is a
% variable (which it will be soon) and to stop it trying to use the built
% in graphics function fcontour(...)
fcontour = 0;
for c1 = 1:numSamples
    clear tempres
    clear ctrlength
    clear fcontour
    eval(['load ' fullfile(DATA(c1).folder, DATA(c1).name) ' -mat']);
    if exist('ctrlength', 'var')
        DATA(c1).ctrlength = ctrlength;
        DATA(c1).length = length(freqContour);
        DATA(c1).contour = freqContour;
    elseif exist('fcontour', 'var')
        DATA(c1).ctrlength = fcontour(length(fcontour))/1000;
        DATA(c1).length = length(fcontour);
        DATA(c1).contour = fcontour(1:DATA(c1).length);
    else
        DATA(c1).ctrlength = freqContour(length(freqContour))/1000;
        DATA(c1).length = length(freqContour)-1;
        DATA(c1).contour = freqContour(1:DATA(c1).length);
=======
cd(path);
path = [path '/*ctr']; %only include files that end in 'ctr'
DATA = dir(path); %creates a structure 'DATA' to hold the list of .ctr files contained in the user-specified folder
DATA = rmfield(DATA,'date'); %remove the extraneous fields that contain the files' metadata
DATA = rmfield(DATA,'datenum');
DATA = rmfield(DATA,'bytes');
DATA = rmfield(DATA,'isdir');
[numSamples x] = size(DATA); %assigns the number of .ctr files that were loaded into the structure DATA (i.e., # of .ctr files in the folder selected) to the variable 'numSamples'
for c1 = 1:numSamples %active contour number, looping from 1 to total number in the folder (the size of DATA)
    clear tempres %removes 'tempres' and 'ctrlength' as variables in the local workspace so they can be created again fresh
    clear ctrlength
    eval(['load ' DATA(c1).name ' -mat']); %loads the active contour name as a .mat file
    if exist('ctrlength', 'var') %if the variable 'ctrlength' exists in the current row c1 (because it's not the first iteration?), assign values to the variables below
        DATA(c1).ctrlength = ctrlength; %load the existing 'ctrlength' value for the current contour (c1)
        DATA(c1).length = length(freqContour); %make the value in the length field the length of 'freqContour'
        DATA(c1).contour = freqContour; % make the value in the contour field the freqContour
    else %if the variable 'ctrlength' doesn't exist (because it's the first contour of the run), assign values based on the following formulas
        DATA(c1).ctrlength = freqContour(length(freqContour))/1000; %ctrlength is the length of freqContour divided by 1000 (why divided by 1000?)
        DATA(c1).length = length(freqContour)-1; %length is the length of freqContour-1
        DATA(c1).contour = freqContour(1:DATA(c1).length); %contour is the freqContour from point 1 thru the length (which is length of freqContour-1 point)
>>>>>>> 08305fa (Add code from Wendi's version on top of Version of 2021-10-01)
```

- `ARTwarp_Run_Categorisation.m`

```
<<<<<<< HEAD
h = findobj('Tag', 'warpFactorLevel');
warpFactorLevel = str2num(get(h, 'String'));

=======
% loading all the variables that were set in 'ARTwarp_Get_Parameters'
>>>>>>> 08305fa (Add code from Wendi's version on top of Version of 2021-10-01)
```

- `warp.m` 

```
<<<<<<< HEAD
parfor i = 1:m
    e1 = u1(i);
    for j = 1:n
        e2 = u2(j);
        M(i,j) = min(e1,e2)/max(e1,e2)*100;        
=======
% moving through reference and active contours one point at a time, calculate (smaller
% value/larger value)*100 to place a similarity score of each point in the
% diagonals of matrix M. 
for i = 1:1:m
    for j = 1:1:n
        M(i,j) = min([u1(i) u2(j)])/max([u1(i) u2(j)])*100;
>>>>>>> 08305fa (Add code from Wendi's version on top of Version of 2021-10-01)
```

and

```
<<<<<<< HEAD
    if round(i/3) <=1;
        j = 1;
        if k(i-1,j) > warpFactorLevel
            y = NaN;
=======
    if round(i/3) <=1; %if the active datapoint of the reference contour divided by 3 is <= 1....
        j = 1; %index of active contour is 1
        if k(i-1,j) > 3
            y = NaN; %AND the value stored at i-1,j is greater than 3, temporary variable 'y' is NaN
>>>>>>> 08305fa (Add code from Wendi's version on top of Version of 2021-10-01)
```

**Comment by alex-konovalov** [comment]
So, the plan now is:
1. Review the changes, mark those where changes have to be reverted (i.e. we need to keep the current version from GitHub, now Wendi's)
2. Resolve conflicts
3. Test
4. Decide what to do with other files provided by Wendi.

**Comment by olexandr-konovalov** [comment]
The only Wendi's comments we did not include were those in `ARTwarp_Load_Data.m` since @michaelstanway rewrote that fragment of code already, and hopefully will submit a PR shortly.

**Pull request merged**
